### ISSUE TITLE
What data is stored?

### ISSUE THREAD

**Issue by friarfool** [FacettsOpen/exodify#2]
Does the extension itself save any of the API calls, thus creating a browsing history of the user?

**Comment by BillCarsonFr** [comment]
Sorry for (very) late response. 
No the extension does not save this, the application just require the 'storage' permission to store a boolean preference settings (you can see the preference in the settings page of the plugin).
Also you can see in the manifest that the app only make calls to 'https://reports.exodus-privacy.eu.org/api/search/*' 

So actually when you visit a google play store page, the addon will make a https call for each app detected in the page to the exodus web site (that is not tracking you). Eventually your browser can catch that, so choose a good browser.
