### ISSUE TITLE
Detect apps on the wishlist

### ISSUE THREAD

**Issue by pnu-s** [FacettsOpen/exodify#4]
The Exodify extension does not detect applications on the Google Play "wishlist" (https://play.google.com/wishlist).
See below:
![image](https://user-images.githubusercontent.com/6069449/51352110-e7f80900-1aac-11e9-97e6-dcf9e1e3e8ae.png)

That would be a very useful feature in order to have statistics on a specified set of applications.
Thank you in advance if you can implement this :).

**Comment by BillCarsonFr** [comment]
Fixed in 0.5.4

**Comment by pnu-s** [comment]
@BillCarsonFr Thanks!

The trackers are now displayed properly but the statistics (usually shown after clicking on the exodify icon) are not showing up. Is it expected behaviour?

![image](https://user-images.githubusercontent.com/6069449/54301466-48905780-45bf-11e9-9f2d-1f8297696196.png)
